development:
  adapter: postgresql
  encoding: unicode
  database: sports_info_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sports_info_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sports_info_prod
  pool: 5
  timeout: 5000